added a basic doc assembly sample for word
WrathOfZombies/samples pull request #13
Opened 2017-02-07 22:44 UTC by JuaneloJuanelo

Created a new sample that uses the basic objects if the API.
1. use styles
2. add paragraphs
3. Search
4. insert content controls.
5. update content controls 
6. insert footnotes.

2017-02-08 03:29 UTC, jakobpn reviewed
Overall looks very good. I wonder if the snippet should be split into more focused snippets: Paragraph/Content Controls, Footer/Headers, Replace content

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +id: ciyvyru7l00014r6ydkzkwka7
I see a ^M at the end of each line in the first section of the file. Not sure how that got there.

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +    $("#InsertHeader").click(InsertHeader);
#InsertHeader -> #insert-header
InsertHeader -> insertHeader

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +    $("#AddParagraphs").click(AddParagraphs);
Ditto for this and the next 3 lines

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +            var myHeader = context.document.body.insertText("This is a sample Heading 1 Title!!", "start");
myHeader -> header

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +            var myHeader = context.document.body.insertText("This is a sample Heading 1 Title!!", "start");
Not sure you need !! at the end of the inserted header

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +
Remove 2 new lines

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +
Remove new line

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +     // Using the WordJS API. Insert a set of paragraphs, a content control and a page break.
Don't need "Using the WordJS API."

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                // Queue a command to add a paragraph at the end of the document. Set the style on the paragraph.
I don't think we need to say "Queue a command to..." in every comment.

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                var myPar = ctx.document.body.insertParagraph("Timeline", "end");
myPar -> paragraph

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +            Word.run(function (ctx) {
ctx -> context

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                var myPar2 = ctx.document.body.insertParagraph("The Services shall commence on July 31, 2015, and shall continue through July 29, 2015.", "end");
ditto on variable name

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                var myPar3 = ctx.document.body.insertParagraph("Project Costs by Phase", "end");
Ditto

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                // Queue a command to add a paragraph at the end of the document. Set the style on the paragraph and wrap the paragraph
Ditto on using Queue

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                var myContentControl = myPar4.insertContentControl();
myContentControl -> contentControl

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                // Synchronize the document state by executing the queued commands,
We should have a discussion on the level of commenting in the samples.

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +      // Using the WordJS API. Search the document for instances of the string "Contoso". Change the font of
Ditto on WordJS API not needed

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +name: Basic Word APIs
Consider calling this "Basic document assembly", if it better describes the theme of the snippet

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                      //  results.items[i].font.color = "#FF0000"    // Change color to Red
Removed code that has // in front of it

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +            Word.run(function (ctx) {
ditto on ctx -> context

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +             Word.run(function (ctx) {
ditto on context

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                var ccs = ctx.document.contentControls.getByTag("customer");
Better variable name than ccs

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +              Word.run(function (ctx) {
ditto on ctx

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                var mySections = ctx.document.sections;
ditto on use of my in variable name

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                    var myFooter = mySections.items[0].getFooter("primary");
my

2017-02-08 03:29 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +                        <span class="ms-Button-label">1. Add H1 Title </span><span class="ms-Button-description">Adds a Title at the beginning of the document.</span>
Is a numbered list needed?

2017-02-09 00:28 UTC, JuaneloJuanelo commented on samples/word/Basics/basic-doc-assembly.yaml
> +id: ciyvyru7l00014r6ydkzkwka7
not sure why this happens I just opened in the editor and it does not show anything.

2017-02-09 01:25 UTC, JuaneloJuanelo reviewed
modified as requested...

2017-02-10 07:24 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +id: ciyvyru7l00014r6ydkzkwka7
@WrathOfZombies , do you know?

2017-02-10 07:28 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +    paragraph4.style = "Normal";
@WrathOfZombies, I'm pretty sure Juan would have indented correctly when he wrote the snippet, so do you now why the indentation is lost here?

2017-02-10 19:21 UTC, jakobpn requested changes

2017-02-10 19:21 UTC, jakobpn commented on samples/word/Basics/custom-properties-access.yaml
> +            var customDocProps = context.document.properties.customProperties;
I suggest you call the var customProperties instead of customDocProps.

2017-02-10 19:21 UTC, jakobpn commented on samples/word/Basics/custom-properties-access.yaml
> +    <p class="ms-font-m">Executes a simple code snippet</p>
Please see samples/excel/range/set-get-values.yaml for the format of the HTML. There should be a introduction, a setup button (if needed), and a set up buttons for each function to try. In this snippet there will only be one. The name of the button should be the function that the snippet will demonstrate.

2017-02-10 19:21 UTC, jakobpn commented on samples/word/Basics/custom-properties-access.yaml
> +id: ciyyoh3d00000456y37cgjdki
The id should be empty ''

2017-02-10 19:21 UTC, jakobpn commented on samples/word/Basics/basic-doc-assembly.yaml
> +    // Create a proxy collection for the sections collection.
Need to fix the identation

2017-02-10 20:32 UTC, JuaneloJuanelo commented on samples/word/Basics/custom-properties-access.yaml
> +    <p class="ms-font-m">Executes a simple code snippet</p>
done

2017-02-10 20:43 UTC, JuaneloJuanelo commented
fixed the isues...

2017-02-10 23:15 UTC, merged