get-slide-metadata snippet for PowerPoint
WrathOfZombies/samples pull request #15
Opened 2017-02-14 23:49 UTC by Rick-Kirkham

Uses the SlideRange coercion type

2017-03-01 22:33 UTC, jakobpn requested changes

2017-03-01 22:33 UTC, jakobpn commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +name: get-slide-metadata
get-side-metadata -> Get slide metadata

2017-03-01 22:33 UTC, jakobpn commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +    function run() {
run -> getSlideMetadata

2017-03-01 22:33 UTC, jakobpn commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +        <span class="ms-Button-label">Run</span>
run -> Get slide metadata

2017-03-01 22:33 UTC, jakobpn commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +    <p class="ms-font-m">Select one or more slides and click <b>Run</b> to get
Change to "Demonstrates how to get slide metadata"

2017-03-01 22:33 UTC, jakobpn commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +                    document.getElementById('output').innerText = JSON.stringify(asyncResult.value);
Output to console instead

2017-03-01 22:33 UTC, jakobpn commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +                    document.getElementById('output').innerText = JSON.stringify(asyncResult.value);
Use console.log(JSON.stringify(asyncResult.value, null, 4));

2017-03-07 21:01 UTC, Rick-Kirkham commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +    function run() {
This conflicts with the guidance in the Readme for wrathofzombies/samples:
"Each button-click handler should have its own async function, called "run" if there is only one button on the page "

2017-03-07 21:07 UTC, Rick-Kirkham commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +    <p class="ms-font-m">Select one or more slides and click <b>Run</b> to get
Users need to be told to select one or more slides. Also, your wording just repeats what the title says, so it seems redundant.

2017-03-07 21:16 UTC, Rick-Kirkham commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +        <span class="ms-Button-label">Run</span>
The pattern with other snippets is to label the button either "Run" or "Run Code".

2017-03-07 21:19 UTC, Rick-Kirkham commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +    <p class="ms-font-m">Select one or more slides and click <b>Run</b> to get
Added that, but kept the original paragraph too. It is needed.

2017-03-07 21:20 UTC, Rick-Kirkham commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +name: get-slide-metadata
done

2017-03-07 21:20 UTC, Rick-Kirkham commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +                    document.getElementById('output').innerText = JSON.stringify(asyncResult.value);
done

2017-03-07 23:22 UTC, jakobpn requested changes

2017-03-07 23:22 UTC, jakobpn commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +    function run() {
OK. I will change the readme file.

2017-03-07 23:22 UTC, jakobpn commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +        <span class="ms-Button-label">Run</span>
Please see samples\excel\range\set-get-values.yaml for the pattern

2017-03-07 23:54 UTC, Rick-Kirkham commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +    function run() {
ok

2017-03-07 23:54 UTC, Rick-Kirkham commented on samples/powerpoint/basics/get-slide-metadata.yaml
> +        <span class="ms-Button-label">Run</span>
ok

2017-03-08 01:08 UTC, merged